# Generated by Django 4.2.11 on 2026-02-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('linea_numero', models.PositiveSmallIntegerField(help_text='Número de línea del cliente (>=1). Único por cliente.')),
                ('estado_linea', models.CharField(choices=[('NO_INSTALADO', 'No Instalado'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('CANCELADO', 'Cancelado')], default='NO_INSTALADO', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('saldo_vencido', models.DecimalField(decimal_places=2, default=0, help_text='Calculado automáticamente por la tarea de cobranza.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Línea de Servicio',
                'verbose_name_plural': 'Líneas de Servicio',
                'ordering': ['cliente', 'linea_numero'],
                'unique_together': {('cliente', 'linea_numero')},
            },
        ),
    ]
