# Generated by Django 4.2.11 on 2026-02-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_rubro', models.CharField(choices=[('NO_PAGADO', 'No Pagado'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulado')], default='NO_PAGADO', max_length=20)),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('linea_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubros', to='lineas.lineaservicio')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='CollectionsRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido')], default='SUCCESS', max_length=10)),
                ('unpaid_count', models.PositiveSmallIntegerField(default=0)),
                ('action_taken', models.CharField(blank=True, choices=[('NONE', 'Sin acción'), ('SUSPEND', 'Suspendido'), ('UNSUSPEND', 'Reactivado')], default='NONE', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('linea_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_logs', to='lineas.lineaservicio')),
            ],
            options={
                'verbose_name': 'Log de Cobranza',
                'verbose_name_plural': 'Logs de Cobranza',
                'ordering': ['-started_at'],
            },
        ),
    ]
